# If adding a new driver, please try to keep the entries alphabetized! :)

[[drivers]]
name = "a4988"
product_url = "https://www.allegromicro.com/en/products/motor-drivers/brush-dc-motor-drivers/a4988"
pololu_url = "https://www.pololu.com/product/1182"

[[drivers]]
name = "drv8825"
product_url = "https://www.ti.com/product/DRV8825"
pololu_url = "https://www.pololu.com/category/154/"

[[drivers]]
name = "stspin220"
product_url = "https://www.st.com/en/motor-drivers/stspin220.html"
pololu_url = "https://www.pololu.com/category/260/"

[[drivers]]
name = "tmc2209"
product_url = "https://www.analog.com/en/products/tmc2209.html"
pololu_url = ""

